import React, { useState, useContext, useEffect, useMemo } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, ShoppingBag, Heart, Star, Search, ChevronRight } from 'lucide-react';
import { CartContext } from '../context/CartContext';
import { ProductContext } from '../context/ProductContext';
import { FavoritesContext } from '../context/FavoritesContext';
import './ProductDetailPage.css';

const ProductDetailPage = () => {
    const { addToCart } = useContext(CartContext);
    const { products } = useContext(ProductContext);
    const { isFavorite, toggleFavorite } = useContext(FavoritesContext);
    const { id } = useParams();
    const navigate = useNavigate();

    // Find the product by parsing params strictly, handling the large IDs generated by Date.now()
    const databaseProduct = products.find(p => p.id.toString() === id.toString());

    const [selectedSize, setSelectedSize] = useState('M');
    const [selectedColor, setSelectedColor] = useState('black');
    const [quantity, setQuantity] = useState(1);
    const [activeTab, setActiveTab] = useState('details');

    const product = useMemo(() => {
        if (!databaseProduct) return null;
        return {
            ...databaseProduct,
            description: databaseProduct.description || 'Crafted from a luxurious fabric, this piece features a timeless silhouette that drapes beautifully. The subtle sheen of the material adds an element of glamour, while the relaxed fit ensures day-long comfort. Complete with refined detailing and expert construction.',
            images: databaseProduct.image ? [databaseProduct.image] : [],
            colors: databaseProduct.colors || [
                { id: 'black', name: 'Midnight Black', hex: '#111111' },
                { id: 'champagne', name: 'Champagne', hex: '#E5D6C5' },
                { id: 'emerald', name: 'Emerald', hex: '#0B4738' }
            ],
            sizes: databaseProduct.sizes || (['accessories', 'beauty', 'home'].includes(databaseProduct.category?.toLowerCase()) ? ['OS'] : ['XS', 'S', 'M', 'L', 'XL']),
            rating: databaseProduct.rating || 4.8,
            reviews: databaseProduct.reviews || (124 + ((parseInt(id, 10) || 100) % 50))
        };
    }, [databaseProduct, id]);

    const [mainImage, setMainImage] = useState(product?.images[0] || '');
    const [zoomStyle, setZoomStyle] = useState({});

    useEffect(() => {
        if (!databaseProduct) {
            navigate('/shop');
        }
    }, [databaseProduct, navigate]);

    if (!product) {
        return <div className="container" style={{ padding: '100px 0', textAlign: 'center' }}>Loading product...</div>;
    }

    const handleMouseMove = (e) => {
        const { left, top, width, height } = e.target.getBoundingClientRect();
        const x = (e.clientX - left) / width * 100;
        const y = (e.clientY - top) / height * 100;
        setZoomStyle({
            transformOrigin: `${x}% ${y}%`,
            transform: 'scale(2)'
        });
    };

    const handleMouseLeave = () => {
        setZoomStyle({
            transformOrigin: 'center center',
            transform: 'scale(1)'
        });
    };

    return (
        <div className="product-page">
            <div className="container">
                {/* Breadcrumb */}
                <div className="breadcrumb">
                    <Link to="/">Home</Link>
                    <ChevronRight size={14} />
                    <Link to="/shop">Shop</Link>
                    <ChevronRight size={14} />
                    <span>{product.name}</span>
                </div>

                <div className="product-layout" key={product.id}>
                    {/* Image Gallery */}
                    <div className="product-gallery">
                        <div className="thumbnail-list">
                            {product.images.map((img, index) => (
                                <button
                                    key={index}
                                    className={`thumbnail-btn ${mainImage === img ? 'active' : ''}`}
                                    onClick={() => setMainImage(img)}
                                >
                                    <img src={img} alt={`Thumbnail ${index + 1}`} />
                                </button>
                            ))}
                        </div>

                        <div
                            className="main-image-container"
                            onMouseMove={handleMouseMove}
                            onMouseLeave={handleMouseLeave}
                        >
                            <img
                                src={mainImage}
                                alt={product.name}
                                className="main-image"
                                style={zoomStyle}
                            />
                        </div>
                    </div>

                    {/* Product Info */}
                    <div className="product-info-section">
                        <h1 className="product-title">{product.name}</h1>
                        <p className="product-price-large">${product.price.toFixed(2)}</p>

                        <div className="product-rating">
                            <div className="stars">
                                {[...Array(5)].map((_, i) => (
                                    <Star key={i} size={16} fill={i < Math.floor(product.rating) ? "var(--color-primary)" : "none"} />
                                ))}
                            </div>
                            <span className="review-count">({product.reviews} Reviews)</span>
                        </div>

                        <p className="product-short-desc">{product.description}</p>

                        <hr className="divider" />

                        {/* Options */}
                        <div className="product-options">
                            <div className="option-group">
                                <div className="option-header">
                                    <span className="option-label">Color:</span>
                                    <span className="option-value">{product.colors.find(c => c.id === selectedColor)?.name}</span>
                                </div>
                                <div className="color-selector">
                                    {product.colors.map(color => (
                                        <button
                                            key={color.id}
                                            className={`color-btn ${selectedColor === color.id ? 'active' : ''}`}
                                            style={{ backgroundColor: color.hex }}
                                            onClick={() => setSelectedColor(color.id)}
                                            title={color.name}
                                        />
                                    ))}
                                </div>
                            </div>

                            <div className="option-group">
                                <div className="option-header">
                                    <span className="option-label">Size:</span>
                                    <a href="#size-guide" className="size-guide-link">Size Guide</a>
                                </div>
                                <div className="size-selector">
                                    {product.sizes.map(size => (
                                        <button
                                            key={size}
                                            className={`size-btn ${selectedSize === size ? 'active' : ''}`}
                                            onClick={() => setSelectedSize(size)}
                                        >
                                            {size}
                                        </button>
                                    ))}
                                </div>
                            </div>

                            <div className="quantity-group">
                                <span className="option-label">Quantity:</span>
                                <div className="quantity-selector">
                                    <button onClick={() => setQuantity(Math.max(1, quantity - 1))}>-</button>
                                    <input type="number" value={quantity} readOnly />
                                    <button onClick={() => setQuantity(quantity + 1)}>+</button>
                                </div>
                            </div>
                        </div>

                        {/* Actions */}
                        <div className="product-actions-main">
                            <button className="btn btn-primary add-to-cart-large" onClick={() => addToCart(product, selectedSize)}>
                                <ShoppingBag size={20} /> Add to Cart
                            </button>
                            <button
                                className="btn btn-outline wishlist-btn-large"
                                onClick={() => toggleFavorite(product)}
                            >
                                <Heart size={20} fill={isFavorite(product.id) ? "black" : "none"} />
                            </button>
                        </div>

                        {/* Accordion Tabs */}
                        <div className="product-tabs">
                            <div className="tab-headers">
                                <button
                                    className={`tab-btn ${activeTab === 'details' ? 'active' : ''}`}
                                    onClick={() => setActiveTab('details')}
                                >
                                    Details
                                </button>
                                <button
                                    className={`tab-btn ${activeTab === 'shipping' ? 'active' : ''}`}
                                    onClick={() => setActiveTab('shipping')}
                                >
                                    Shipping & Returns
                                </button>
                            </div>

                            <div className="tab-content">
                                {activeTab === 'details' && (
                                    <ul className="details-list">
                                        <li>Outer: 70% Viscose, 30% Silk</li>
                                        <li>Lining: 100% Polyester</li>
                                        <li>Dry clean only</li>
                                        <li>Cool iron on reverse</li>
                                        <li>Model is 5'10" and wears size S</li>
                                    </ul>
                                )}
                                {activeTab === 'shipping' && (
                                    <div className="shipping-info">
                                        <p><strong>Free Standard Shipping</strong> on orders over $300 (3-5 business days).</p>
                                        <p>Express Shipping available at checkout.</p>
                                        <p>Free returns within 30 days of purchase. Items must be unworn with tags attached.</p>
                                    </div>
                                )}
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            {/* Detailed Long Description Section */}
            {(product.longDescription || product.description) && (
                <div className="product-long-description-section bg-light">
                    <div className="container" style={{ padding: '4rem 2rem', maxWidth: '800px', margin: '0 auto', textAlign: 'center' }}>
                        <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '2rem', marginBottom: '1.5rem', color: 'var(--color-primary)' }}>
                            Behind the Design
                        </h2>
                        <div
                            style={{
                                fontSize: '1.05rem',
                                lineHeight: '1.8',
                                color: 'var(--color-text-light)',
                                whiteSpace: 'pre-line' // Allows preserving line breaks from textarea
                            }}
                        >
                            {product.longDescription || "This piece represents the perfect harmony of contemporary design and traditional craftsmanship. Every thread has been carefully selected to ensure not just stunning visual appeal, but lasting comfort and durability. This item is designed seamlessly to transition from day to evening, making it an indispensable addition to your wardrobe. The meticulous attention to detail is evident in every stitch, reflecting our brand's commitment to uncompromising quality and timeless elegance."}
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default ProductDetailPage;
