/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useState, useEffect } from 'react';
import { products as initialProducts } from '../data/products';

export const ProductContext = createContext();

export const ProductProvider = ({ children }) => {
    // Initialize products from localStorage and merge with static array
    const [products, setProducts] = useState(() => {
        const savedProducts = localStorage.getItem('luxeaura_products');
        if (savedProducts) {
            const parsed = JSON.parse(savedProducts);
            // Preserve custom products added by the user (IDs generated by Date.now() are > 1000)
            // But always refresh the stock catalog from initialProducts so category structures don't break
            const customProducts = parsed.filter(p => p.id > 1000);

            // Map over initial products to preserve any edits made to them in local storage
            // CRITICAL: Strictly enforce category and subcategory from coreProd so navigation doesn't break from old local storage!
            const refreshedInitial = initialProducts.map(coreProd => {
                const storedEdit = parsed.find(p => p.id === coreProd.id);
                return storedEdit ? { ...coreProd, ...storedEdit, category: coreProd.category, subcategory: coreProd.subcategory } : coreProd;
            });

            return [...customProducts, ...refreshedInitial];
        }
        return initialProducts;
    });

    // Save products to localStorage whenever they change
    useEffect(() => {
        localStorage.setItem('luxeaura_products', JSON.stringify(products));
    }, [products]);

    // Function to add a new product created by the user
    const addProduct = (newProduct) => {
        const productWithId = {
            ...newProduct,
            id: Date.now(), // Generate a unique ID
            price: parseFloat(newProduct.price),
            isNewArrival: true, // Make it show up on the front page
            isFeatured: false,
            isBestseller: false,
        };
        // Add to the front of the list
        setProducts(prev => [productWithId, ...prev]);
    };

    // Function to update an existing product
    const editProduct = (id, updatedData) => {
        setProducts(prev => prev.map(product =>
            product.id === id ? { ...product, ...updatedData, price: parseFloat(updatedData.price) } : product
        ));
    };

    // Function to delete a product
    const deleteProduct = (id) => {
        setProducts(prev => prev.filter(product => product.id !== id));
    };

    return (
        <ProductContext.Provider value={{ products, addProduct, editProduct, deleteProduct }}>
            {children}
        </ProductContext.Provider>
    );
};
